#!/bin/bash

# Define network interfaces
WAN_IF="ens33"   # External (WAN) interface
LAN_IF="ens37"   # Internal (LAN) interface

# Flush existing iptables rules
iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -X

# Set default policies
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Allow unlimited traffic on the loopback interface
iptables -A INPUT -i lo -j ACCEPT

# Allow incoming traffic on the LAN interface
iptables -A INPUT -i $LAN_IF -j ACCEPT

# Allow established and related incoming connections on the WAN interface
iptables -A INPUT -i $WAN_IF -m state --state ESTABLISHED,RELATED -j ACCEPT

# Enable NAT for the LAN interface
iptables -t nat -A POSTROUTING -o $WAN_IF -j MASQUERADE

# Allow forwarding of established and related connections
iptables -A FORWARD -i $WAN_IF -o $LAN_IF -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow forwarding from LAN to WAN
iptables -A FORWARD -i $LAN_IF -o $WAN_IF -j ACCEPT

# Enable IP forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
