#!/bin/bash

sudo hostnamectl set-hostname LinRouter

sudo cat <<EOT > /etc/netplan/00-installer-config.yaml
network:
  ethernets:
    lan_1:
      addresses:
        - 192.168.10.254/24
      match:
        macaddress: $1
      set-name: lan_1
    lan_2:
      addresses:
        - 192.168.20.254/24
      match:
        macaddress: $2
      set-name: lan_2
    lan_3:
      addresses:
        - 192.168.30.254/24
      match:
        macaddress: $3
      set-name: lan_3
    outside:
      dhcp4: true
      match:
        macaddress: $4
      set-name: outside
  version: 2
EOT

sudo netplan apply
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -p
