#!/bin/bash

sudo hostnamectl set-hostname LinRouter

sudo cat <<EOT > /etc/netplan/00-installer-config.yaml
network:
  ethernets:
    ens33:
      addresses:
        - 10.0.10.254/24
    ens38:
      addresses:
        - 10.0.20.254/24
    lan_3:
      addresses:
        - 10.0.30.254/24
    outside:
      dhcp4: true
  version: 2
EOT

sudo netplan apply
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -p
